"""add owner_id to notes

Revision ID: a7fea0fa10fa
Revises:
Create Date: 2026-08-24 14:29:53.620639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7fea0fa10fa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Notes", sa.Column("owner_id", sa.Integer(), nullable=True))

    op.execute('UPDATE "Notes" SET owner_id = 1 WHERE owner_id IS NULL')

    op.alter_column("Notes", "owner_id", nullable=False)

    op.create_foreign_key(None, "Notes", "Users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Notes", type_="foreignkey")
    op.drop_column("Notes", "owner_id")
    # ### end Alembic commands ###
